title: adyOS Docs
description: The documentation for the JavaScript pseudo-operating system adyOS.
theme: just-the-docs

url: https://ady.tomcat.sh

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
