title: adyOS Docs
description: The documentation for the JavaScript pseudo-operating system adyOS.
theme: just-the-docs

url: https://ady.tomcat.sh

aux_links:
  adyOS Repo: https://git.tomcat.sh/adyos
  adyDocs Repo: https://git.tomcat.sh/adyos-docs-page
  adyPM Default Repository Repo: https://git.tomcat.sh/adyos-default-repo

color_scheme: dark_with_purple

favicon_ico: "./icon.ico"
logo: "./icon.png"
